version: "3.7"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: develop
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - actix-web-postgres:/var/lib/postgresql/data
      # 初回起動時にsqlを実行
      # - ./docker/db:/docker-entrypoint-initdb.d
volumes:
  actix-web-postgres:
