openapi: 3.0.0
info:
  title: actix-web-sample.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: base endpoint.
paths:
  /:
    get:
      summary: Return "Hello world!".
      description: tutorial
      responses:
        '200':    # status code
          description: sample
  /users:
    post:
      tags:
        - "users"
      responses:
        '201':
          description: create user
    get:
      tags:
        - "users"
      responses:
        '200':
          description: find users
  /users/{id}:
    get:
      tags:
        - "users"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minItems: 1
      responses:
        '200':
          description: find user
    put:
      tags:
        - "users"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minItems: 1
      responses:
        '200':
          description: update user
    delete:
      tags:
        - "users"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minItems: 1
      responses:
        '204':
          description: delete user
